Internally use binaries from the original / preferably

diff --git a/transient-file-view b/transient-file-view
--- a/transient-file-view
+++ b/transient-file-view
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 NEXT_OPTION_LOOKAHEAD='(?=,exclude=.|,snapshot|,overlay|,toleratepartialtransfer|$)'
+ORIGINAL_PATH="$PATH"
 
 function silence_stderr {
 	"$@" 2>/dev/null
@@ -9,8 +10,10 @@ function silence_stderr {
 
 FINAL_FUSER_UMOUNT_DIRS=()
 FINAL_UMOUNT_DIRS=()
+FINAL_BIND_UMOUNTS=()
 function clean_final {
 	exitCode=$?
+	set_oldroot_path
 
 	cd /
 	local dir
@@ -18,6 +21,12 @@ function clean_final {
 		fusermount -u "$dir" 2>/dev/null
 		if [[ "$(findmnt --noheadings -o FSTYPE "$dir")" == "fuse.fuse-overlayfs" ]]; then
 			fusermount -z -u "$dir" 2>/dev/null
+		fi
+	done
+	for bind_mount in "${FINAL_BIND_UMOUNTS[@]}"; do
+		if ! umount "$bind_mount" 2>/dev/null; then
+			echo "Error: Failed to umount \"$bind_mount\", aborting." >&2
+			exit 1
 		fi
 	done
 	for dir in "${FINAL_UMOUNT_DIRS[@]}"; do
@@ -68,7 +77,7 @@ function assert_valid_file {
 }
 
 function usage {
-	echo "Transient File View 0.6.1-PRE"
+	echo "Transient File View 0.7.0-PRE"
 	echo "Usage: $(basename "$0") [--help] [--verbose|--debug] file [file]* [-- command [ARG]...]"
 	echo
 	echo "Create transient views of files or directories in a user namespace. This creates a new mount namespace with"
@@ -109,6 +118,12 @@ function mount_oldroot {
 		echo "Error: mount --rbind failed: $MOUNT_OUT" >&2
 		return 255
 	fi
+	set_oldroot_path
+}
+
+# Set PATH so that it takes binaries from the original / preferably.
+function set_oldroot_path {
+	PATH="$MAIN_TMP_DIR/oldroot${PATH//:/:$MAIN_TMP_DIR/oldroot}:$PATH"
 }
 
 function handle_directory {
@@ -147,6 +162,7 @@ function handle_directory {
 			echo "Error: Mounting tmpfs to \"$DIRECTORY\": $MOUNT_OUT" >&2
 			return 255
 		fi
+		FINAL_BIND_UMOUNTS+=("$DIRECTORY")
 
 		if [[ "$DIRECTORY_OPTIONS" =~ ,toleratepartialtransfer(,|$) ]]; then
 			TAR_ARGS+=("--ignore-failed-read")
@@ -220,6 +236,7 @@ function handle_file {
 		echo "Error: Mounting \"$TMP_FILE\" to \"$FILE\": \"$MOUNT_OUT\"." >&2
 		return 255
 	fi
+	FINAL_BIND_UMOUNTS+=("$FILE")
 }
 
 if [ "$1" == "--help" ]; then
@@ -317,6 +334,7 @@ if [[ "$(unshare --help)" =~ --map-user ]]; then
 	UNSHARE=(unshare --map-user "$MAP_USER" --map-group "$MAP_GROUP" --)
 fi
 
+PATH="$ORIGINAL_PATH"
 COMMAND=()
 # No command given, start bash with a custom prompt prefix
 if [ "$#" -lt 1 ]; then
